---
# make sure homebrew is installed, update brew and install applications 

- name: install applications
  include: homebrew.yml

# - name: download files
#   get_url:
#     url: "{{item.value.url}}"
#     dest: "{{item.value.dest}}"
#   with_dict: "{{downloads}}"    

- name: install homebrew applications
  homebrew:
    name: "{{item}}"
    state: latest
  with_items: "{{applications}}"

- name: install homebrew cask applications
  homebrew_cask:
    name: "{{item}}"
    state: installed 
  with_items: "{{cask_applications}}"
